### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by TimoGlastra** [dbluhm/pydid#48]
I couldn't find any license associated with this project (maybe I'm not looking in the right place). No license means no one is allowed to use it

**Comment by dbluhm** [comment]
Thanks for pointing this out. This is an error on my part  I'll upload a license file for Apache 2 ASAP.

**Comment by dbluhm** [comment]
License file added. While it was previously missing, at least the pyproject.toml indicated the intended license from early in the repo history :grimacing:
